development:
  adapter: postgresql
  database: swagfm_development
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  database: swagfm_test
  username: postgres
  password:
  host: localhost
